baseURL : 'https://lin-roger.github.io/'
languageCode : 'en-us'
title : 'Flowey & Code'
theme : "PaperMod"
math: true

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary

taxonomies:
    tag: tags


menu:
    main:
      - name: Archive
        pageRef: archives
        weight: 10
      - name: Search
        pageRef: search
        weight: 20
      - name: Tags
        pageRef: tags
        weight: 30

params:
    ShowReadingTime: true
    ShowToc: true
    TocOpen: true
    ShowBreadCrumbs: true
    ShowPostNavLinks: true
    ShowCodeCopyButtons: true
    hideFooter: true

    assets:
        favicon: "flowey.png"

    label:
        text: "flowey & code"
        icon: "flowey.png"
        iconHeight: 30

    homeInfoParams:
        Title: Flowey & Code ğŸŒº
        Content: >
            æ­¡è¿ä½ ä¾†åˆ°å°èŠ±çš„å¿«æ¨‚åŸå§‹ç¢¼

            - é€™è£¡ç´€éŒ„è‘—æˆ‘çš„ç”Ÿæ´»ï¼Œä½ å¯ä»¥åœ¨é€™è£¡çœ‹åˆ°æŠ€è¡“åˆ†äº«ã€è«–æ–‡è§£æå’Œç”Ÿæ´»ç¢å¿µç­‰

    socialIcons: # optional
        - name: github
          url: "https://github.com/lin-roger"
        - name: twitter
          url: "https://twitter.com/ah_flowey"
    
    buttons:
        - name: Archive
          url: "/archive"
        - name: Github
          url: "https://github.com/"
    
